# Generated by Django 5.0.6 on 2024-05-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
