# Generated by Django 5.0.6 on 2024-09-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Author of the Post', on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(help_text='Category name', through='NewsPortal.PostCategory', to='NewsPortal.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of post', max_length=128),
        ),
    ]
