# Generated by Django 5.0.6 on 2024-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0008_alter_post_author_alter_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='This is the help text'),
        ),
    ]
